<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'>
<title>Python Exceptions</title>
<link href='style.css' rel='stylesheet'>
<link href='//dash_ref/Category/Built-in Exceptions/1'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when assert statement fails/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when attribute assignment or reference fails/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when the input() function hits end-of-file condition/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a floating point operation fails/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a generator&#39;s close() method is called/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when the imported module is not found/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when index of a sequence is out of range/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a key is not found in a dictionary/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when the user hits interrupt key (CTRL+C or Delete)/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when an operation runs out of memory/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a variable is not found in local or global scope/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised by abstract methods/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when system operation causes system related error/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when result of an arithmetic operation is too large to be represented/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a weak reference proxy is used to access a garbage collected referent/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when an error does not fall under any other category/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised by next() function to indicate that there is no further item to be returned by iterator/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised by parser when syntax error is encountered/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when there is incorrect indentation/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when indentation consists of inconsistent tabs and spaces/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when interpreter detects internal error/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised by sys.exit() function/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a function or operation is applied to an object of incorrect type/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a reference is made to a local variable in a function or method, but no value has been bound to that variable/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related encoding or decoding error occurs/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related error occurs during encoding/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related error occurs during decoding/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related error occurs during translating/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when a function gets argument of correct type but improper value/0'>
<link href='//dash_ref_Built-in Exceptions/Entry/Raised when second operand of division or modulo operation is zero/0'>
</head>
<body>
<header>
<h1>Python Exceptions</h1>
</header>
<article>
<p></p>
<section class='category'>
<h2 id='//dash_ref/Category/Built-in Exceptions/1'>
Built-in Exceptions
</h2>
<div class='scrollable'>
<table>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when assert statement fails/0'>
<td class='command'>
<p>
<code>AssertionError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when <code>assert</code> statement fails</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when attribute assignment or reference fails/0'>
<td class='command'>
<p>
<code>AttributeError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when attribute assignment or reference fails</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when the input() function hits end-of-file condition/0'>
<td class='command'>
<p>
<code>EOFError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when the <code>input()</code> function hits end-of-file condition</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a floating point operation fails/0'>
<td class='command'>
<p>
<code>FloatingPointError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a floating point operation fails</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a generator&#39;s close() method is called/0'>
<td class='command'>
<p>
<code>GeneratorExit</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a generator&#39;s <code>close()</code> method is called</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when the imported module is not found/0'>
<td class='command'>
<p>
<code>ImportError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when the imported module is not found</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when index of a sequence is out of range/0'>
<td class='command'>
<p>
<code>IndexError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when index of a sequence is out of range</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a key is not found in a dictionary/0'>
<td class='command'>
<p>
<code>KeyError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a key is not found in a dictionary</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when the user hits interrupt key (CTRL+C or Delete)/0'>
<td class='command'>
<p>
<code>KeyboardInterrupt</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when the user hits interrupt key (<code>CTRL+C</code> or <code>Delete</code>)</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when an operation runs out of memory/0'>
<td class='command'>
<p>
<code>MemoryError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when an operation runs out of memory</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a variable is not found in local or global scope/0'>
<td class='command'>
<p>
<code>NameError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a variable is not found in local or global scope</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised by abstract methods/0'>
<td class='command'>
<p>
<code>NotImplementedError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised by abstract methods</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when system operation causes system related error/0'>
<td class='command'>
<p>
<code>OSError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when system operation causes system related error</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when result of an arithmetic operation is too large to be represented/0'>
<td class='command'>
<p>
<code>OverflowError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when result of an arithmetic operation is too large to be represented</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a weak reference proxy is used to access a garbage collected referent/0'>
<td class='command'>
<p>
<code>ReferenceError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a weak reference proxy is used to access a garbage collected referent</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when an error does not fall under any other category/0'>
<td class='command'>
<p>
<code>RuntimeError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when an error does not fall under any other category</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised by next() function to indicate that there is no further item to be returned by iterator/0'>
<td class='command'>
<p>
<code>StopIteration</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised by <code>next()</code> function to indicate that there is no further item to be returned by iterator</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised by parser when syntax error is encountered/0'>
<td class='command'>
<p>
<code>SyntaxError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised by parser when syntax error is encountered</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when there is incorrect indentation/0'>
<td class='command'>
<p>
<code>IndentationError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when there is incorrect indentation</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when indentation consists of inconsistent tabs and spaces/0'>
<td class='command'>
<p>
<code>TabError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when indentation consists of inconsistent tabs and spaces</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when interpreter detects internal error/0'>
<td class='command'>
<p>
<code>SystemError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when interpreter detects internal error</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised by sys.exit() function/0'>
<td class='command'>
<p>
<code>SystemExit</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised by <code>sys.exit()</code> function</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a function or operation is applied to an object of incorrect type/0'>
<td class='command'>
<p>
<code>TypeError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a function or operation is applied to an object of incorrect type</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a reference is made to a local variable in a function or method, but no value has been bound to that variable/0'>
<td class='command'>
<p>
<code>UnboundLocalError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a reference is made to a local variable in a function or method, but no value has been bound to that variable</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related encoding or decoding error occurs/0'>
<td class='command'>
<p>
<code>UnicodeError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when an Unicode-related encoding or decoding error occurs</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related error occurs during encoding/0'>
<td class='command'>
<p>
<code>UnicodeEncodeError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when an Unicode-related error occurs during encoding</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related error occurs during decoding/0'>
<td class='command'>
<p>
<code>UnicodeDecodeError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when an Unicode-related error occurs during decoding</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when an Unicode-related error occurs during translating/0'>
<td class='command'>
<p>
<code>UnicodeTranslateError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when an Unicode-related error occurs during translating</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when a function gets argument of correct type but improper value/0'>
<td class='command'>
<p>
<code>ValueError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when a function gets argument of correct type but improper value</p>
</div>
<div class='notes'></div>
</td>
</tr>
<tr id='//dash_ref_Built-in Exceptions/Entry/Raised when second operand of division or modulo operation is zero/0'>
<td class='command'>
<p>
<code>ZeroDivisionError</code>
</p>
</td>
<td class='description'>
<div class='name'><p>Raised when second operand of division or modulo operation is zero</p>
</div>
<div class='notes'></div>
</td>
</tr>
</table>
</div>
</section>
<section class='notes'>
<h2>Notes</h2>
<ul>
<li>Based on the cheat sheet from <a href="https://www.programiz.com/python-programming/exceptions">Programiz</a>.</li>
<li>Converted and extended by <a href="https://github.com/tomy0000000">tomy0000000</a>.</li>
</ul>

</section>
</article>
<footer>
You can modify and improve this cheat sheet <a onclick="window.dash.openExternal_(this.href); return false;" href="http://cheat.kapeli.com">here</a>
</footer>
</body>
</html>
